### PR TITLE
stratum.go

### PR DESCRIPTION
**Pull request by lodos2005**
Nicehash Stratum Desteği.

### CODE REVIEW

**Comment by lodos2005** [comment]
added Qtminer and Nicehash Support.

**Comment by etherninja** [comment]
does this work? i cant seem to get it to work

**Comment by sammy007** [comment]
I see no NH stratum implementation in this PR.

**Comment by trustfarm-dev** [comment]
NiceHash configuration examples.
It's from NiceHash official answer, interfacing with open-ethereum-pool

Not support : dagger-hasimoto pool checking.
But, Support : NiceHash hash.

configuration.

stratum+tcp://etc.trustfarm.io:28008   <--- pool stratum address and port 
Username and Password : 0x8dfxxxxxx(walletaddress):# ⇐ Should be '#' 

Tested Result : sometimes Delta - Reject ratio has arise.
At that time, in the view of pool logs, there's rejected hash because of "Duplicate share submit"
It's come from  NiceHash side or Nicehash Proxy error or fake miner rigs mal-operations.

So, I've enabled pool configuration to dobule check submitted PoW .

In this case feedback to NiceHash, then Nicehash will check.
now, most of nicehash submits has works well.

**Comment by etherninja** [comment]
I have seen at times duplicates equal valids. I can only sit by and watch the miner get kicked.

**Comment by sammy007** [comment]
This is shit, not a PR.

**Pull request closed without merging**
