### PR TITLE
Add a config option which lets you choose if transaction fees are kept as pool fees.

### PR DESCRIPTION
**Pull request by jameshilliard**
This needs to be reviewed, I tested that it compiles but I'm not sure the best way to test that it works as expected.

### CODE REVIEW

**Comment by subtly** [comment]
Looks okay to me. @sammy007 Can you confirm?

**Comment by sammy007** [comment]
No, it's negligent. I wonder if all config options are lowerCamelCase why make new one CamelCase.

`"KeepTXFees": false,`
``json:"keepTXFees"``

Does it even work?

Also there is a convention in code already `extraTxReward`. So it must be `TxFees`, not `TXFees`.

If pool cutting fees included in block mined block reward should not include tx fees, it must be 5 Ether in `/#/blocks` page.

Also https://github.com/erlang/otp/wiki/Writing-good-commit-messages

**Comment by sammy007** [comment]
I will add this feature to `develop` soon (tm) after some testing. Rewrote it a bit.

**Comment by sammy007** [comment]
The idea is:

```
-       reward.Add(reward, extraTxReward)
+       if !u.config.KeepTxFees {
+               reward.Add(reward, extraTxReward)
+       }
```

**Comment by jameshilliard** [comment]
@sammy007 I had done it using subtraction and addition when calculating profit to make sure that extraTxReward gets sent to the pool fee wallet address, does that still happen if you just don't add it to the rewards instead?

**Comment by sammy007** [comment]
```
@@ -211,7 +212,9 @@ func (u *BlockUnlocker) handleBlock(block *rpc.GetBlockReply, candidate *storage
        if err != nil {
                return fmt.Errorf("Error while fetching TX receipt: %v", err)
        }
-       reward.Add(reward, extraTxReward)
+       if !u.config.KeepTxFees {
+               reward.Add(reward, extraTxReward)
+       }

        // Add reward for including uncles
        rewardForUncles := big.NewInt(0).Mul(uncleReward, big.NewInt(int64(len(block.Uncles))))
@@ -220,6 +223,7 @@ func (u *BlockUnlocker) handleBlock(block *rpc.GetBlockReply, candidate *storage
        candidate.Orphan = false
        candidate.Hash = block.Hash
        candidate.Reward = reward
+       candidate.ExtraTxReward = extraTxReward
        return nil
 }

@@ -445,6 +449,11 @@ func (u *BlockUnlocker) calculateRewards(block *storage.BlockData) (*big.Rat, *b

        rewards := calculateRewardsForShares(shares, block.TotalShares, minersProfit)

+       if u.config.KeepTxFees {
+               extraTxReward := new(big.Rat).SetInt(block.ExtraTxReward)
+               poolProfit.Add(poolProfit, extraTxReward)
+       }
```

If you cut fees no need to add it to block reward which is going to stats page.

**Comment by jameshilliard** [comment]
@sammy007 Oh, I thought it was intended that the stats page shows block rewards before the fee is taken out(I'm assuming extraTxReward is the pool fee instead of a flat percentage).

**Comment by sammy007** [comment]
It does, but I think it's fair to show that block reward does not include mining fees.

**Comment by jameshilliard** [comment]
@sammy007 Is that how it works for flat percentage based fees?

**Comment by sammy007** [comment]
I pushed to `develop`. This is my vision of how it must be implemented. Miners will see block reward before flat fees, if you have `keepTxFees` enabled miners will see static block reward or static block reward + extra reward for uncle inclusion.

Makes sense if you have many miners and frequent payouts.

**Pull request closed without merging**
