### PR TITLE
Implement score based reward system

### PR DESCRIPTION
**Pull request by CryptoManiac**
Dear dev, please say NO to pool hoppers. :)

### CODE REVIEW

**Comment by CryptoManiac** [comment]
Generally it's still the same proportional system, but uses exponential share weighting.

The main idea is a distribution of rewards according to proportion of miner's score in the total pool score. Share score is calculated using this simple formula:

```S = share_diff * exp(cumulative_diff / network_diff)```

Where ```cumulative_diff``` is a sum of difficulty for all shares in the current round.

**Comment by sammy007** [comment]
Last time I tried to add slush scoring to redis backend I found that it can overflow. Also I found that it's impossible to make it without normalization. I will look into your implementation, but keep in mind that I have almost 0 time to work on this project.

Also, https://github.com/sammy007/open-ethereum-pool/pull/107/commits/2303d834eb220d128768adee3965baf7c76ba23a#diff-98a54c0bc01c582672a56b060f606b81R249

^^ Why duplicate redis commands?

**Comment by CryptoManiac** [comment]
Hi. It's correct that classical slush scoring would likely to overflow since it uses a function of time. That's why I'm using a function of luck, so maximum ratio will be only ~2.72 @ 100% luck, ~7.38 @ 200% or ~22026 @ 1000%. I'd say that these are not so great values to have int64 overflow issues while having reasonable values of network difficulty. However, it seems that int64 won't be sufficient in the future, when network difficulty will reach very big values. Some kind of normalization will be required even for simple proportional system.

>> Why duplicate redis commands

We still need to account shares in order to calculate luck properly. So I decided to store these values in separate keys. I remember that there is no command to get values of multiple keys for hash types so this copy-paste solution was my preference.

**Comment by CryptoManiac** [comment]
Replaced with #112.

**Pull request closed without merging**
